# Generated by Django 3.2.13 on 2022-11-12 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('net_id', models.CharField(max_length=30)),
                ('room_num', models.CharField(max_length=30)),
                ('start_time', models.CharField(max_length=30)),
            ],
        ),
    ]
