# Generated by Django 3.2.13 on 2022-11-12 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='start_time',
            new_name='start_date',
        ),
    ]
