# Generated by Django 4.1.3 on 2022-11-12 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_rename_start_time_bookings_start_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookings",
            old_name="start_date",
            new_name="start_time",
        ),
    ]
